# This file was generated by GoReleaser. DO NOT EDIT.
cask "kubectl-tsp" do
  version "13.0.6"

  on_macos do
    on_intel do
      sha256 "b719da0e2a0573705c004dbb18f55b1f50704094f0a7223117de15c01b720e21"
      url "https://github.com/cudneys/tsp/releases/download/v#{version}/kubectl-tsp_#{version}_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "eff95faf1cfb6551332d49fef6b9e0a733afef39c88d2c836c3fdfa757339987"
      url "https://github.com/cudneys/tsp/releases/download/v#{version}/kubectl-tsp_#{version}_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "9739cfc294bb423d4587d5dab3a5f2b412b0f027ab06aad67f90cd13eb57ee17"
      url "https://github.com/cudneys/tsp/releases/download/v#{version}/kubectl-tsp_#{version}_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "40ba71a3163bc0cf995b8daac8cc4ee7305837cce99ca4ad0687e09ea49d334b"
      url "https://github.com/cudneys/tsp/releases/download/v#{version}/kubectl-tsp_#{version}_linux_arm64.tar.gz"
    end
  end

  name "kubectl-tsp"
  desc "kubectl plugin that deploys an ephemeral network troubleshooting pod"
  homepage "https://github.com/cudneys/tsp"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "kubectl-tsp"

  postflight do
    if system_command("/usr/bin/xattr", args: ["-h"]).exit_status == 0
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/kubectl-tsp"]
    end
  end

  # No zap stanza required

  caveats <<~EOS
    Installed as a kubectl plugin. Invoke it with:
      kubectl tsp
  EOS
end
