# This file was generated by GoReleaser. DO NOT EDIT.
cask "kubectl-tsp" do
  version "13.0.4"

  on_macos do
    on_intel do
      sha256 "82d752b58382973db872165ac66513d66064262e4738bc1ede9a0bb9f4e80018"
      url "https://github.com/cudneys/tsp/releases/download/v#{version}/kubectl-tsp_#{version}_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "0febdf4a1c1916fbf43c9cea7777686c55c1b9c1b2c51de900b004059d575925"
      url "https://github.com/cudneys/tsp/releases/download/v#{version}/kubectl-tsp_#{version}_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "268973ecbb1dc3710a24c3a8a3f08cb8f143e73799e8a2bdb6548fc6fa91f069"
      url "https://github.com/cudneys/tsp/releases/download/v#{version}/kubectl-tsp_#{version}_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "1efd67bf691f9e325a7ca74c72b89afec865901f9da06ddc442372415ae4203a"
      url "https://github.com/cudneys/tsp/releases/download/v#{version}/kubectl-tsp_#{version}_linux_arm64.tar.gz"
    end
  end

  name "kubectl-tsp"
  desc "kubectl plugin that deploys an ephemeral network troubleshooting pod"
  homepage "https://github.com/cudneys/tsp"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "kubectl-tsp"

  # No zap stanza required

  caveats <<~EOS
    Installed as a kubectl plugin. Invoke it with:
      kubectl tsp
  EOS
end
