# This file was generated by GoReleaser. DO NOT EDIT.
cask "kubectl-tsp" do
  version "13.0.7"

  on_macos do
    on_intel do
      sha256 "817a2149077a6cd61c345a3cd34c7ce6d616f4a308461021189ede896cc9de5c"
      url "https://github.com/cudneys/tsp/releases/download/v#{version}/kubectl-tsp_#{version}_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "5f33e7d28211a3136e2d288b1a0c6d01d0f0868c4ba1acd8ff9ba2ddffec9dfd"
      url "https://github.com/cudneys/tsp/releases/download/v#{version}/kubectl-tsp_#{version}_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "7ec66320e25d5131f2b06e623269e2b8dde6ce1f780025aa864d9e2d1cb9b2e4"
      url "https://github.com/cudneys/tsp/releases/download/v#{version}/kubectl-tsp_#{version}_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "a6c07534b4bec7919ed9d56db691f377f35f4d3c93830ce7e926afbdebc9bb46"
      url "https://github.com/cudneys/tsp/releases/download/v#{version}/kubectl-tsp_#{version}_linux_arm64.tar.gz"
    end
  end

  name "kubectl-tsp"
  desc "kubectl plugin that deploys an ephemeral network troubleshooting pod"
  homepage "https://github.com/cudneys/tsp"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "kubectl-tsp"

  postflight do
    if system_command("/usr/bin/xattr", args: ["-h"]).exit_status == 0
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/kubectl-tsp"]
    end
  end

  # No zap stanza required

  caveats <<~EOS
    Installed as a kubectl plugin. Invoke it with:
      kubectl tsp
  EOS
end
